views:
  - title: Resumen
    icon: mdi:home
    path: overview
    badges:
      - entity: person.dani
      - entity: person.eva
      - entity: sensor.home_meantemperature
        name: Temp. Media
      - entity: switch.home_heater_switch
        name: Calefacción
      - entity: sensor.electricperiod
    cards:
      - type: thermostat
        entity: climate.home_thermostat
        name: Termostato
      - title: Calefacción
        type: entities
        show_header_toggle: false
        state_color: true
        entities:
          - entity: climate.home_thermostat
            name: Termostato
          - entity: automation.home_thermostat_turnupthetemperatureatmorning
            name: Subir Temp. a 22º a las 06:00
      - type: weather-forecast
        entity: weather.openweathermap
        show_forecast: true
      - type: weather-forecast
        entity: weather.casa_gande
        show_forecast: true
      - type: custom:pvpc-hourly-pricing-card
        name: "PVPC 2.0 DHA"
        entity: sensor.pvpc

  - title: Planta Baja
    icon: mdi:home-floor-0
    path: ground-floor
    badges:
      - entity: person.dani
      - entity: person.eva
      - entity: sensor.groundfloor_meantemperature
        name: Temp. Media
      - entity: switch.home_heater_switch
        name: Calefacción
      - entity: sensor.electricperiod
    cards:
      - type: thermostat
        entity: climate.groundfloor_thermostat
        name: Termostato
      - title: Salón
        type: entities
        show_header_toggle: false
        state_color: true
        entities:
          - type: section
          - entity: climate.livingroom_thermostat
            name: Termostato
            secondary_info: last-changed
          - entity: sensor.livingroom_hub_humidity
            name: Humedad
            secondary_info: last-changed
          - type: section
          - entity: media_player.livingroom_television
            name: Televisión
          - entity: media_player.xbox_systemos
            name: Xbox One
          - entity: media_player.livingroom_xiaomimiboxs
            name: Mi Box S
          - type: section
          - entity: light.wled_0149bc
            name: Árbol de Navidad
            secondary_info: last-changed
          - type: section
            label: Luz Acuario
          - entity: switch.livingroom_aquariumplug_autoswitch
            name: Apagar/Encender Automáticamente
          - type: conditional
            conditions:
              - entity: switch.livingroom_aquariumplug_autoswitch
                state: "on"
            row:
              entity: sensor.livingroom_aquariumplug_nextturnoff
              name: Próximo Apagado
          - type: conditional
            conditions:
              - entity: switch.livingroom_aquariumplug_autoswitch
                state: "on"
            row:
              entity: sensor.livingroom_aquariumplug_nextturnon
              name: Próximo Encendido
          - entity: switch.livingroom_aquariumplug_switch
            name: Apagar/Encender
      - title: Entrada
        type: entities
        show_header_toggle: false
        state_color: true
        entities:
          - type: section
          - entity: camera.entrance_camera
            name: Cámara
      - title: Cocina
        type: entities
        entities:
          - type: section
          - entity: climate.kitchen_thermostat
            name: Termostato
            secondary_info: last-changed
          - entity: sensor.kitchen_hub_humidity
            name: Humedad
            secondary_info: last-changed
          - type: section
          - entity: switch.kitchen_dishwasher_switch
            name: Lavavajillas
        show_header_toggle: false
        state_color: true
      - title: Lavadero
        type: entities
        entities:
          - type: section
          - entity: switch.utility_washingmachine_switch
            name: Lavadora
        show_header_toggle: false
        state_color: true
      - title: Garaje
        type: entities
        entities:
          - type: section
          - entity: sensor.garage_hub_temperature
            name: Temperatura
            secondary_info: last-changed
          - entity: sensor.garage_hub_humidity
            name: Humedad
            secondary_info: last-changed
          - type: section
          - entity: camera.garage_camera
            name: Cámara
        show_header_toggle: false
        state_color: false

  - title: Primera Planta
    icon: mdi:home-floor-1
    path: first-floor
    badges:
      - entity: person.dani
      - entity: person.eva
      - entity: sensor.firstfloor_meantemperature
        name: Temp. Media
      - entity: switch.home_heater_switch
        name: Calefacción
      - entity: sensor.electricperiod
    cards:
      - type: thermostat
        entity: climate.firstfloor_thermostat
        name: Termostato
      - title: Dormitorio Niños
        type: entities
        show_header_toggle: false
        state_color: true
        entities:
          - type: section
          - entity: climate.kidsbedroom_thermostat
            name: Termostato
            secondary_info: last-changed
          - entity: sensor.kidsbedroom_hub_humidity
            name: Humedad
            secondary_info: last-changed
          - type: section
            label: Modo Noche
          - entity: switch.kidsbedroom_nightplug_autoswitch
            name: Apagar/Encender Automáticamente
          - type: conditional
            conditions:
              - entity: switch.kidsbedroom_nightplug_autoswitch
                state: "on"
            row:
              entity: sensor.kidsbedroom_nightplug_nextturnoff
              name: Próximo Apagado
          - type: conditional
            conditions:
              - entity: switch.kidsbedroom_nightplug_autoswitch
                state: "on"
            row:
              entity: sensor.kidsbedroom_nightplug_nextturnon
              name: Próximo Encendido
          - entity: switch.kidsbedroom_nightplug_switch
            name: Apagar/Encender
      - title: Dormitorio Principal
        type: entities
        show_header_toggle: false
        state_color: true
        entities:
          - type: section
          - entity: climate.masterbedroom_thermostat
            name: Termostato
            secondary_info: last-changed
          - entity: sensor.masterbedroom_hub_humidity
            name: Humedad
            secondary_info: last-changed
          - type: section
          - entity: media_player.masterbedroom_television
            name: Televisión
          - type: section
            label: Modo Noche
          - entity: switch.masterbedroom_nightplug_autoswitch
            name: Apagar/Encender Automáticamente
          - type: conditional
            conditions:
              - entity: switch.masterbedroom_nightplug_autoswitch
                state: "on"
            row:
              entity: sensor.masterbedroom_nightplug_nextturnoff
              name: Próximo Apagado
          - type: conditional
            conditions:
              - entity: switch.masterbedroom_nightplug_autoswitch
                state: "on"
            row:
              entity: sensor.masterbedroom_nightplug_nextturnon
              name: Próximo Encendido
          - entity: switch.masterbedroom_nightplug_switch
            name: Apagar/Encender

  - title: Segunda Planta
    icon: mdi:home-floor-2
    path: second-floor
    badges:
      - entity: person.dani
      - entity: person.eva
      - entity: sensor.secondfloor_meantemperature
        name: Temp. Media
      - entity: switch.home_heater_switch
        name: Calefacción
      - entity: sensor.electricperiod
    cards:
      - type: thermostat
        entity: climate.secondfloor_thermostat
        name: Termostato
      - title: Despacho
        type: entities
        show_header_toggle: false
        state_color: true
        entities:
          - type: section
          - entity: climate.office_thermostat
            name: Termostato
            secondary_info: last-changed
          - entity: sensor.office_hub_humidity
            name: Humedad
            secondary_info: last-changed

  - title: Sistema
    icon: mdi:engine
    path: system
    badges:
      - entity: person.dani
      - entity: person.eva
      - entity: sensor.home_meantemperature
        name: Temp. Media
      - entity: switch.home_heater_switch
        name: Calefacción
      - entity: sensor.electricperiod
    cards:
      - title: Baterias
        type: entities
        show_header_toggle: false
        state_color: true
        entities:
          - type: section
          - entity: sensor.mobility_phone_dani_nivel_de_la_bateria
            name: Móvil Dani - Batería
          - entity: sensor.iphone_de_eva_battery_level
            name: Móvil Eva - Batería
      - title: Termostatos
        type: entities
        show_header_toggle: false
        state_color: true
        entities:
          - type: section
          - climate.home_thermostat
          - group.home_heaters_group
          - switch.home_heater_switch
          - type: section
          - climate.groundfloor_thermostat
          - climate.kitchen_thermostat
          - climate.livingroom_thermostat
          - type: section
          - climate.firstfloor_thermostat
          - climate.kidsbedroom_thermostat
          - climate.masterbedroom_thermostat
          - type: section
          - climate.secondfloor_thermostat
          - climate.office_thermostat
      - title: Conectividad
        type: entities
        show_header_toggle: false
        state_color: true
        entities:
          - type: section
          - binary_sensor.home_heater_status
          - type: section
          - binary_sensor.kitchen_dishwasher_status
          - binary_sensor.kitchen_hub_status
          - binary_sensor.utility_washingmachine_status
          - binary_sensor.garage_hub_status
          - binary_sensor.livingroom_aquariumplug_status
          - binary_sensor.livingroom_hub_status
          - type: section
          - binary_sensor.kidsbedroom_hub_status
          - binary_sensor.kidsbedroom_nightplug_status
          - binary_sensor.masterbedroom_hub_status
          - binary_sensor.masterbedroom_nightplug_status
          - type: section
          - binary_sensor.office_hub_status