sensor:
  - platform: template
    sensors:
      electricperiod:
        friendly_name: "Periodo Eléctrico"
        unique_id: electricperiod
        value_template: >-
          {% set values = {"P1": "Punta", "P2": "Llano", "P3": "Valle"} %}
          {{ values[state_attr('sensor.pvpc', 'period')] }}
        icon_template: >-
          {% set icons = {"P1": "mdi:brightness-5", "P2": "mdi:brightness-6", "P3": "mdi:brightness-2"} %}
          {{ icons[state_attr('sensor.pvpc', 'period')] }}
