homeassistant:
  customize:
    person.dani:
      icon: mdi:face
    person.eva:
      icon: mdi:face-woman

person:
  - name: Dani
    id: !secret user_dani_id
    device_trackers:
      - device_tracker.mobility_phone_dani
  - name: Eva
    id: !secret user_eva_id
    device_trackers:
      - device_tracker.iphone_de_eva
